# Generated by Django 4.2.11 on 2024-05-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_group_join_code_for_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Join code'),
        ),
        migrations.AlterField(
            model_name='group',
            name='join_code_for_instructor',
            field=models.CharField(max_length=20, unique=True, verbose_name='Join code for instructor'),
        ),
    ]
