# Generated by Django 4.2.11 on 2024-05-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('panel', '0004_alter_group_join_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='function_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='function_starter',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.group'),
            preserve_default=False,
        ),
    ]
