# Generated by Django 4.2.11 on 2024-06-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_group_image_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='max_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
