# Generated by Django 4.2.11 on 2024-06-08 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_task_end_date_task_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
