# Generated by Django 4.2.11 on 2024-06-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_solution_submitted_at_alter_solution_solution_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='function_starter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
