# Generated by Django 4.2.11 on 2024-06-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_task_function_starter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
