# Generated by Django 4.2.11 on 2024-06-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_testcase_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='max_points',
            field=models.IntegerField(default=10),
        ),
    ]
