# Generated by Django 4.2.11 on 2024-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_solution_points_task_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_plagiarism_checked',
            field=models.BooleanField(default=False),
        ),
    ]
