# Generated by Django 4.2.11 on 2024-06-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_task_is_plagiarism_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_solutions_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Plagiarism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0)),
                ('solution_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarisms_as_solution_one', to='panel.solution')),
                ('solution_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarisms_as_solution_second', to='panel.solution')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarisms', to='panel.task')),
            ],
        ),
    ]
